import * as fs from 'node:fs'
import * as path from 'node:path'
import { describe, expect, test } from 'vitest'

const appRoot = path.resolve(import.meta.dirname, '..')
const repositoryRoot = path.resolve(appRoot, '../..')

function read(relativePath: string): string {
  return fs.readFileSync(path.join(appRoot, relativePath), 'utf8')
}

function record(value: unknown, label: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new TypeError(`${label} must be an object`)
  }
  return value as Record<string, unknown>
}

describe('Openloop native credential sheet boundary', () => {
  test('has no browser credential entry point or credential capability', () => {
    for (const relativePath of [
      'src/credentials.html',
      'src/credentials.ts',
      'src/credentials.css',
      'src-tauri/capabilities/credentials.json',
      'src-tauri/permissions/autogenerated/credentials_set.toml',
      'src-tauri/permissions/autogenerated/credentials_unset.toml',
      'src-tauri/permissions/autogenerated/credentials_status.toml',
    ]) {
      expect(fs.existsSync(path.join(appRoot, relativePath)), relativePath).toBe(false)
    }
  })

  test('uses one frontend entry and exposes no plaintext credential IPC command', () => {
    const viteConfig = read('vite.config.ts')
    const tauriConfig = read('src-tauri/tauri.conf.json')
    const buildScript = read('src-tauri/build.rs')
    const library = read('src-tauri/src/lib.rs')
    const browserSources = fs.readdirSync(path.join(appRoot, 'src'))
      .filter(filename => filename.endsWith('.ts') || filename.endsWith('.html'))
      .map(filename => read(`src/${filename}`))
      .join('\n')

    expect(viteConfig).toContain("main: resolve(import.meta.dirname, 'index.html')")
    expect(viteConfig).not.toMatch(/credentials/u)
    const config = record(JSON.parse(tauriConfig) as unknown, 'Tauri config')
    const app = record(config.app, 'Tauri app config')
    const security = record(app.security, 'Tauri security config')
    expect(security.capabilities).toEqual(['main'])
    expect(buildScript).not.toMatch(/credentials_(?:set|unset|status)/u)
    expect(library).not.toMatch(
      /#\s*\[\s*tauri::command\s*\][^]*?fn\s+credentials_(?:set|unset|status)/u,
    )
    expect(browserSources).not.toMatch(/credentials_(?:set|unset|status)/u)
    expect(browserSources).not.toMatch(/__OPENLOOP_CREDENTIAL_PROMPT_TOKEN__/u)
  })

  test('keeps replacement and plaintext resolution on separate native bridge surfaces', () => {
    const credentialModule = read('src-tauri/src/credentials/mod.rs')
    const bridgePolicy = fs.readFileSync(
      path.join(repositoryRoot, 'packages/openloop/desktop-bridge-host/src/remote.ts'),
      'utf8',
    )

    expect(credentialModule).toContain('mod secure_sheet;')
    expect(credentialModule).not.toContain('mod secure_prompt;')
    expect(credentialModule).toContain('"openCredentialReplacement"')
    expect(credentialModule).toContain('"resolveCredential"')
    expect(bridgePolicy).toMatch(
      /BROWSER_SAFE_METHODS[\s\S]*'openCredentialReplacement'/u,
    )
    expect(bridgePolicy).toMatch(/HOST_ONLY_METHODS[\s\S]*'resolveCredential'/u)
  })
})
