/** Repository policy for the model-visible Cordis Service and Event catalogs. */

import type { CordisCatalogPolicy } from '@deepseek-ai/dsh-typert-generator'

const FOUNDATION_TYPE_NAMES: ReadonlySet<string> = new Set([
  'AbortSignal',
  'AsyncIterable',
  'Context',
  'Error',
  'Map',
  'Partial',
  'Pick',
  'Promise',
  'Record',
  'Readonly',
  'Uint8Array',
])

export const CORDIS_CONTEXT_SCAN_EXEMPTIONS: Readonly<Record<string, string>> = {
  agent: 'Agent.ctx convenience accessor, not a service binding.',
  appExit: 'Launcher-provided process exit callback.',
  cmdlineArgs: 'Launcher-provided immutable argument accessor.',
  configuredAgentIdentities: 'Launcher-provided boot value.',
  launcherSessionQueryPath: 'Launcher-provided session query path.',
  dshHomePath: 'Boot-provided Harness home accessor.',
  launchEnvironment: 'Launcher-provided environment snapshot.',
  connection: 'Client interface service whose implementation has a different declaration name.',
  appShell: 'Client browser service.',
  settingsScope: 'Client settings transport service.',
  chatFileMentions: 'Client slot accessor.',
  commandUi: 'Client command service.',
  conversation: 'Client conversation service.',
  conversationEvents: 'Client conversation event registry.',
  conversationViews: 'Client conversation view registry.',
  layout: 'Client layout service.',
  locale: 'Client locale service.',
  modelDirectories: 'Client model directory service.',
  modules: 'Client module service.',
  remote: 'Client gateway accessor.',
  sessionLogDownload: 'Client session export controller.',
  inputTriggers: 'Client input trigger service.',
  timer: 'Client dynamic-package timer service.',
  slots: 'Client slot registry.',
  theme: 'Client theme service.',
  workspaces: 'Client workspace service.',
}

export const CORDIS_EVENT_SCAN_EXEMPTIONS: Readonly<Record<string, string>> = {
  'command/executed': 'Client command acknowledgement.',
  'connection/reset': 'Client transport signal.',
  'locale/change': 'Client locale signal.',
  'slash/input-begin-command': 'Client slash-input protocol.',
  'slash/input-consume-token': 'Client slash-input protocol.',
  'slash/input-insert-reference': 'Client slash-input protocol.',
  'slash/input-insert-text': 'Client slash-input protocol.',
  'slots/changed': 'Client slot invalidation signal.',
  'theme/change': 'Client theme signal.',
}

const RUNTIME_TYPE_EXEMPTIONS = Object.fromEntries([
  'Agent',
  'AgentStatus',
  'ApprovalOutcome',
  'ApprovalRequest',
  'ApprovalService',
  'AssembleContext',
  'CodeDispatchLog',
  'ContentBlock',
  'CordisInspectQueryRequest',
  'CordisInspectQueryResolved',
  'CredentialRef',
  'DomainChanged',
  'DynamicCordisPackage',
  'DynamicCordisRequestResolved',
  'DynamicCordisRetracted',
  'DynamicCordisRunRequest',
  'FsObservation',
  'FsTarget',
  'FsVersion',
  'FsWriteIntent',
  'GenerateOptions',
  'GoalChanged',
  'LlmCallConfig',
  'LlmFailure',
  'LlmRuntime',
  'PostToolDecision',
  'PreStepDecision',
  'PreToolDecision',
  'PromptAssembly',
  'RequestErrorAction',
  'ResolvedRetryPolicy',
  'Scoped',
  'Session',
  'SessionEvent',
  'SessionId',
  'SessionStartSource',
  'SessionTelemetryRecord',
  'SettingsNamespace',
  'SettingsUpdateSource',
  'StreamChunk',
  'SubagentProvider',
  'SubagentRunEndInfo',
  'SubagentRunInfo',
  'SubagentRuntime',
  'SystemPrompt',
  'ToolDispatchExecution',
  'ToolExecution',
  'ToolExecutionResult',
  'ToolRuntime',
  'UserMessage',
  'WorkflowAgentEndInfo',
  'WorkflowAgentInfo',
  'WorkflowResultInfo',
  'WorkflowRunInfo',
  'AdapterRegistrationHandle',
  'AgentFactory',
  'AgentHandle',
  'AgentOptions',
  'AgentPreset',
  'ApprovalPolicy',
  'ApprovalRequestId',
  'AskUserQuestionAnswer',
  'AskUserQuestionRequest',
  'BashEnvContributor',
  'BashEnvVariableInfo',
  'ClientResponse',
  'CodeRunRequest',
  'CodeRunResult',
  'CommandDefinition',
  'CommandDescriptor',
  'CommandExecution',
  'CommandId',
  'CompactionAgentContext',
  'CompactionResult',
  'CompactionTrigger',
  'ConfinedArgv',
  'ContinuableSetupContribution',
  'ContinuableStart',
  'ContinuableStartSpec',
  'CordisDynamicPackageId',
  'CordisDynamicPluginId',
  'CordisDynamicPluginRunId',
  'CordisDynamicRunMode',
  'CordisErrorDetails',
  'CordisInspectPlatform',
  'CordisInspectProviderManifest',
  'CordisInspectProviderView',
  'CordisInspectQueryResolution',
  'CordisInspectRequestId',
  'CordisInspectResolveAck',
  'CreateAgentOptions',
  'CreateGoalRequest',
  'CreateGoalResult',
  'CreateSessionOptions',
  'CredentialInfo',
  'DirectoryPickerCapability',
  'DirectoryRegistrationHandle',
  'Domain',
  'DomainImpl',
  'DomainSpec',
  'DshEnvironment',
  'DynamicCordisClientSource',
  'DynamicCordisDefineReceipt',
  'DynamicCordisDefineRequest',
  'DynamicCordisHostHalfResult',
  'DynamicCordisInventoryRow',
  'DynamicCordisInvokeResult',
  'DynamicCordisPackageInspection',
  'DynamicCordisPluginInspection',
  'DynamicCordisReference',
  'DynamicCordisRenderFailure',
  'DynamicCordisResolveAck',
  'DynamicCordisRunResolution',
  'DynamicCordisRunResponse',
  'DynamicCordisSnapshotRow',
  'DynamicCordisStopResponse',
  'DynamicCordisUndefineReceipt',
  'EditGoalRequest',
  'EpochHeader',
  'FsDirEntry',
  'FsEditOutcome',
  'FsEditRequest',
  'FsInfo',
  'FsPathInfo',
  'FsWriteOutcome',
  'GoalBlockReason',
  'GoalRef',
  'GoalView',
  'HostCordisInspectProviderRegistration',
  'ImageAttachmentRef',
  'InvariantInstaller',
  'InvokeRemoteRequest',
  'JobDoneListener',
  'JobId',
  'JobRead',
  'JobSnapshot',
  'JobStart',
  'JobsChangedListener',
  'JsonValue',
  'KnobState',
  'LlmAdapter',
  'LlmConfigurableProvider',
  'LlmDiscoveredModel',
  'LlmModelDiscoveryRequest',
  'LlmModelInfo',
  'LlmProviderInfo',
  'LlmResolvedModelInfo',
  'LspProvider',
  'LspQueryRequest',
  'LspQueryResult',
  'ManualCompactAgentContext',
  'Message',
  'MessageFeedbackDeleteRequest',
  'MessageFeedbackDeleteResult',
  'MessageFeedbackListRequest',
  'MessageFeedbackListResult',
  'MessageFeedbackPutRequest',
  'MessageFeedbackPutResult',
  'MessageId',
  'ModelSelection',
  'PermissionSelect',
  'PrepareSessionOptions',
  'PreparedLlmCall',
  'PreparedReferencedMessage',
  'PresetOption',
  'PresetSpec',
  'ProjectionChangeListener',
  'ProjectionCheckpoint',
  'ProjectionDefinition',
  'ProjectionSnapshot',
  'PromptContext',
  'PromptSection',
  'PruneResult',
  'ResolvedCredential',
  'ResumeAgentOptions',
  'RpcReceipt',
  'Sandbox',
  'SandboxExecutionPolicy',
  'SandboxMode',
  'SandboxPolicy',
  'SandboxPolicyRequest',
  'SaveImageAttachment',
  'SaveTextSpill',
  'ScopeKey',
  'SessionEventReadRequest',
  'SessionEventRecord',
  'SessionEventResultFilter',
  'SessionEventSearchDocument',
  'SessionEventSearchPage',
  'SessionEventSearchRequest',
  'SessionEventTraceObservation',
  'SessionEventTraceRequest',
  'SessionEventWindow',
  'SessionForkSource',
  'SessionHeader',
  'SessionInspection',
  'SessionLineageTrace',
  'SessionLocation',
  'SessionLogSnapshot',
  'SessionPersistenceSnapshot',
  'SessionPreparation',
  'SessionProjectionMap',
  'SessionRawArtifact',
  'SessionRecord',
  'SessionReferenceCandidate',
  'SessionReferenceInput',
  'SessionResultFilter',
  'SessionSearchExecContext',
  'SessionSearchHit',
  'SessionSearchPage',
  'SessionSearchRequest',
  'SessionSurfaceSnapshot',
  'SessionTitleObservation',
  'SessionTitleObservationResult',
  'SessionTitleProvider',
  'SessionTitleSnapshot',
  'SettingsDescribeOptions',
  'SettingsDescriptor',
  'SettingsPathOp',
  'SettingsRegisterOptions',
  'SettingsScope',
  'ShellExecRequest',
  'ShellExecSpec',
  'ShellProcess',
  'ShellRunResult',
  'SkillCatalogSnapshot',
  'SkillDefinition',
  'SkillProvider',
  'SkillProviderControl',
  'SkillRegistration',
  'SkillSummary',
  'SkillViewOptions',
  'SpillRef',
  'StorageForms',
  'StoredImageAttachment',
  'SubagentDescendantListEntry',
  'SubagentFollowupOptions',
  'SubagentInterruptAuthority',
  'SubagentListEntry',
  'SubagentReportOptions',
  'SubagentRun',
  'SubagentStartRequest',
  'SubprocessHandle',
  'SubprocessSpawnSpec',
  'SubprocessTerminalHandle',
  'SubprocessTerminalSpawnSpec',
  'TerminalBackend',
  'TerminalReadRequest',
  'TerminalReadResult',
  'TerminalSendOperation',
  'TerminalSendRequest',
  'TerminalSessionId',
  'TerminalSessionSnapshot',
  'TerminalSignal',
  'TerminalSignalResult',
  'TerminalSpawnRequest',
  'TerminalSpawnResult',
  'TokenMeasurement',
  'ToolDefinition',
  'ToolExecutionInput',
  'ToolExecutionMode',
  'ToolGuard',
  'ToolPresentationMode',
  'ToolProviderResult',
  'ToolRestriction',
  'ToolSchema',
  'TypertContribution',
  'TypertDisposer',
  'TypertFace',
  'TypertPackageFilter',
  'TypertPackageRecord',
  'TypertSchemaFilter',
  'TypertSchemaRecord',
  'UserQuestionProvider',
  'WebBootGraph',
  'WebFetchProvider',
  'WebFetchRequest',
  'WebFetchResult',
  'WebRoute',
  'WebSearchProvider',
  'WebSearchRequest',
  'WebSearchResult',
  'WebUpgradeRoute',
  'WorkflowRun',
  'WorkflowStartRequest',
  'Workspace',
  'WorkspaceId',
  'z',
  'z.core.JSONSchema.BaseSchema',
  'z.core.ToJSONSchemaParams',
].map(name => [name, 'Included in the model-visible runtime API type closure.']))

export const CORDIS_INSPECT_POLICY: CordisCatalogPolicy = {
  linkedTypePages: {},
  foundationTypeNames: FOUNDATION_TYPE_NAMES,
  typeLinkExemptions: RUNTIME_TYPE_EXEMPTIONS,
  runtimeServiceExclusions: new Set(['cordisInspect', 'dynamicCordisRunner', 'runtimeBootstrap']),
  runtimeServices: [{
    key: 'timer',
    type: 'TimerService',
    abstract: false,
    doc: 'Disposable timer helpers mixed into Cordis contexts.',
    source: 'vendor/timer/src/index.ts:12',
    methods: [
      {
        signature: 'timeout(callback: () => void, delay: number): () => void',
        jsDoc: '/** Run a callback once and return its disposer. */',
      },
      {
        signature: 'timeout(delay: number): Promise<void>',
        jsDoc: '/** Resolve after a delay; disposal rejects the pending promise. */',
      },
      {
        signature: 'interval(callback: () => void, delay: number): () => void',
        jsDoc: '/** Run a callback repeatedly and return its disposer. */',
      },
      {
        signature: 'interval<R = any>(delay: number): AsyncIterableIterator<void, R, void>',
        jsDoc: '/** Return an async iterator of timer ticks. */',
      },
      {
        signature: 'throttle<F extends (...args: any[]) => void>(callback: F, delay: number, noTrailing?: boolean): F & { dispose: () => void }',
        jsDoc: '/** Return a throttled function whose timer is disposed with the current fiber. */',
      },
      {
        signature: 'debounce<F extends (...args: any[]) => void>(callback: F, delay: number): F & { dispose: () => void }',
        jsDoc: '/** Return a debounced function whose timer is disposed with the current fiber. */',
      },
    ],
  }],
  inheritedEvents: [
    { name: 'internal/plugin', summary: 'A plugin fiber was created.', source: 'vendor/cordis/src/events.ts:328' },
    { name: 'internal/status', summary: 'A fiber changed lifecycle state.', source: 'vendor/cordis/src/events.ts:330' },
    { name: 'internal/service', summary: 'Interception hook for a service binding (no core producer).', source: 'vendor/cordis/src/events.ts:332' },
    { name: 'internal/update', summary: 'Waterfall: a fiber config update is being applied.', source: 'vendor/cordis/src/events.ts:334' },
    { name: 'internal/get', summary: 'Waterfall: a service is being read from the store.', source: 'vendor/cordis/src/events.ts:336' },
    { name: 'internal/set', summary: 'Waterfall: a service is being written to the store.', source: 'vendor/cordis/src/events.ts:338' },
    { name: 'internal/listener', summary: 'A listener was registered.', source: 'vendor/cordis/src/events.ts:340' },
    { name: 'internal/dispatch', summary: 'An event is being dispatched to listeners.', source: 'vendor/cordis/src/events.ts:342' },
    { name: 'hmr/change', summary: 'A watched source file changed on disk.', source: 'vendor/hmr/src/index.ts:20' },
    { name: 'hmr/reload', summary: 'Plugins are being reloaded after a change.', source: 'vendor/hmr/src/index.ts:21' },
    { name: 'exit', summary: 'The process is exiting on a signal.', source: 'vendor/loader/src/index.ts:23' },
    { name: 'loader/config-update', summary: 'The loader config tree changed.', source: 'vendor/loader/src/index.ts:24' },
    { name: 'loader/entry-init', summary: 'A config entry is being initialized.', source: 'vendor/loader/src/index.ts:25' },
    { name: 'loader/partial-dispose', summary: 'An entry is being partially disposed on reload.', source: 'vendor/loader/src/index.ts:26' },
    { name: 'loader/patch-context', summary: 'A context is being patched during a reload.', source: 'vendor/loader/src/index.ts:27' },
  ],
  inheritedServices: [
    { name: 'ctx.on / ctx.once', summary: 'Register an event listener (disposable).', source: 'vendor/cordis/src/events.ts:34' },
    { name: 'ctx.emit / ctx.parallel / ctx.serial / ctx.bail / ctx.waterfall', summary: 'Dispatch an event (sync / awaited / first-bail / short-circuit chain).', source: 'vendor/cordis/src/events.ts:34' },
    { name: 'ctx.plugin / ctx.inject', summary: 'Load a plugin / declare required services.', source: 'vendor/cordis/src/registry.ts:164' },
    { name: 'ctx.effect', summary: 'Register a disposable side effect tied to the fiber.', source: 'vendor/cordis/src/fiber.ts:9' },
    { name: 'ctx.get / ctx.set / ctx.provide / ctx.accessor / ctx.mixin', summary: 'Low-level service-store access and binding.', source: 'vendor/cordis/src/reflect.ts:7' },
    { name: 'ctx.extend / ctx.isolate / ctx.intercept', summary: 'Derive a child context (scoped services / isolation / interception).', source: 'vendor/cordis/src/context.ts:42' },
    { name: 'ctx.root / ctx.scope / ctx.fiber / ctx.registry / ctx.reflect / ctx.events / ctx.logger', summary: 'Ambient handles onto the running context graph.', source: 'vendor/cordis/src/context.ts:16' },
    { name: 'ctx.timer (+ interval / timeout / throttle / debounce)', summary: 'Disposable timer helpers. The `timer` key is provided at runtime; the four supported helpers are mixed onto ctx directly (declared via Pick).', source: 'vendor/timer/src/index.ts:4' },
    { name: 'ctx.loader', summary: 'The config Loader that booted the app (present under the loader).', source: 'vendor/loader/src/index.ts:30' },
    { name: 'ctx.hmr', summary: 'The hot-module-reload watcher (present under the hmr plugin).', source: 'vendor/hmr/src/index.ts:15' },
  ],
}
