import { spawnSync } from 'node:child_process'
import { readFileSync, rmSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
  SERVICE_API as HOST_SERVICE_API,
  queryServiceApi as queryHostServiceApi,
} from '../packages/extensions/tool-cordis/src/api-catalog.ts'

const repositoryRoot = fileURLToPath(new URL('..', import.meta.url))
const tsxCli = fileURLToPath(new URL('../node_modules/tsx/dist/cli.mjs', import.meta.url))
const catalogs = [
  'packages/extensions/tool-cordis/src/api-catalog.ts',
  'packages/extensions/cordis-client-runner/src/client/api-catalog.ts',
] as const

function runCheck() {
  return spawnSync(
    process.execPath,
    [tsxCli, 'scripts/gen-cordis-inspect-catalog.ts', '--check'],
    { cwd: repositoryRoot, encoding: 'utf8' },
  )
}

describe('Cordis inspect catalog generator', () => {
  it('checks both runtime catalogs without rewriting them', () => {
    const before = catalogs.map(path => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8'))
    const result = runCheck()

    expect(result.error).toBeUndefined()
    expect(result.status, `${result.stdout}${result.stderr}`).toBe(0)
    expect(result.stdout).toContain('2 runtime catalog(s) are up to date')

    for (const [index, path] of catalogs.entries()) {
      const after = readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
      expect(after).toBe(before[index])
      expect(after).toContain('Generated by scripts/gen-cordis-inspect-catalog.ts')
      expect(after).not.toContain('gen-cordis-api')
      expect(after).not.toContain('doc-sync')
      expect(after).not.toContain('docs/cordis-catalog')
    }
  }, 90_000)

  it('keeps the Host-only runtime bootstrap out of model-visible catalogs', () => {
    const hostSource = readFileSync(new URL(`../${catalogs[0]}`, import.meta.url), 'utf8')
    const clientSource = readFileSync(new URL(`../${catalogs[1]}`, import.meta.url), 'utf8')

    expect(hostSource).not.toContain("key: 'runtimeBootstrap'")
    expect(HOST_SERVICE_API.some(service => service.key === 'runtimeBootstrap')).toBe(false)
    expect(() => queryHostServiceApi('runtimeBootstrap')).toThrow('no catalogued Service named "runtimeBootstrap"')

    expect(clientSource).not.toContain("key: 'runtimeBootstrap'")
  })

  it('rejects a Context declaration that the Typert projection cannot see', () => {
    const probe = new URL('../packages/util/brand/src/cordis-inspect-probe.ts', import.meta.url)
    writeFileSync(probe, `
declare module '@deepseek-ai/cordis' {
  interface Context {
    openloopCatalogProbe?: string
  }
}

export {}
`)

    try {
      const result = runCheck()
      const output = `${result.stdout}${result.stderr}`

      expect(result.error).toBeUndefined()
      expect(result.status, output).toBe(1)
      expect(output).toContain('ctx.openloopCatalogProbe')
    } finally {
      rmSync(probe, { force: true })
    }
  }, 90_000)
})
