/** Generate the runtime allowlist for repository-owned durable Session events. */

import { globSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve, sep } from 'node:path'
import ts from 'typescript'

const root = resolve(import.meta.dirname, '..')
const output = 'packages/core/session/src/known-event-types.ts'
const sessionTypesModule = '@deepseek-ai/dsh-session/types'
const sessionOwnerPrefix = 'packages/core/session/'

function collectEventTypes(): string[] {
  const eventTypes = new Map<string, string>()
  const problems: string[] = []
  let owner: string | undefined
  const files = globSync('packages/*/*/src/**/*.ts', { cwd: root })
    .map(path => path.split(sep).join('/'))
    .sort()

  for (const file of files) {
    const source = readFileSync(resolve(root, file), 'utf8')
    if (!source.includes('SessionEventMap')) continue
    const sourceFile = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true)

    for (const statement of sourceFile.statements) {
      if (ts.isInterfaceDeclaration(statement) && statement.name.text === 'SessionEventMap') {
        if (!file.startsWith(sessionOwnerPrefix)) {
          problems.push(`${file}: top-level SessionEventMap is outside its owning package.`)
          continue
        }
        if (!statement.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.ExportKeyword)) {
          problems.push(`${file}: owning SessionEventMap must be exported.`)
        }
        if (owner !== undefined) {
          problems.push(`${file}: owning SessionEventMap is already declared in ${owner}.`)
        } else {
          owner = file
        }
        collectMembers(statement, file, sourceFile, eventTypes, problems)
        continue
      }

      if (!ts.isModuleDeclaration(statement)
        || !ts.isStringLiteral(statement.name)
        || statement.name.text !== sessionTypesModule
        || statement.body === undefined
        || !ts.isModuleBlock(statement.body)) continue

      for (const declaration of statement.body.statements) {
        if (ts.isInterfaceDeclaration(declaration) && declaration.name.text === 'SessionEventMap') {
          collectMembers(declaration, file, sourceFile, eventTypes, problems)
        }
      }
    }
  }

  if (owner === undefined) problems.push('the owning SessionEventMap declaration is missing.')
  if (problems.length > 0) {
    throw new Error(`gen-session-event-types: ${problems.length} declaration violation(s):\n${problems.map(problem => `  ${problem}`).join('\n')}`)
  }
  return [...eventTypes.keys()].sort()
}

function collectMembers(
  declaration: ts.InterfaceDeclaration,
  file: string,
  sourceFile: ts.SourceFile,
  eventTypes: Map<string, string>,
  problems: string[],
): void {
  if (declaration.heritageClauses?.length) {
    problems.push(`${file}: SessionEventMap cannot use extends.`)
  }
  for (const member of declaration.members) {
    if (!ts.isPropertySignature(member) || member.type === undefined) {
      problems.push(`${file}: every SessionEventMap member must be a typed property.`)
      continue
    }
    if (!ts.isStringLiteral(member.name)) {
      problems.push(`${file}: SessionEventMap member ${member.name.getText(sourceFile)} must use a string-literal event name.`)
      continue
    }
    const name = member.name.text
    const prior = eventTypes.get(name)
    if (prior !== undefined) {
      problems.push(`${file}: event '${name}' is already declared in ${prior}.`)
      continue
    }
    eventTypes.set(name, file)
  }
}

function render(eventTypes: readonly string[]): string {
  return [
    '/**',
    ' * Generated by scripts/gen-session-event-types.ts; do not edit by hand.',
    ' * Run `pnpm run gen-session-event-types` to regenerate and',
    ' * `pnpm run verify-session-event-types` to verify freshness.',
    ' * @module @deepseek-ai/dsh-session/known-event-types',
    ' */',
    '',
    '/**',
    ' * Every `SessionEventMap` member declared in this repository - the event',
    ' * vocabulary this build understands. The persistence read path refuses to',
    ' * interpret a log containing a type outside this set unless the event',
    " * carries the envelope's `ignorable` marker (see `SessionEvent.ignorable`",
    ' * in `./types.ts`): such a log was likely written by a newer harness, and',
    ' * silently skipping a required event would reconstruct a wrong session.',
    ' * Downstream plugin events are outside this list until a registration',
    ' * mechanism defines their compatibility contract.',
    ' */',
    'export const KNOWN_SESSION_EVENT_TYPES: ReadonlySet<string> = new Set([',
    ...eventTypes.map(name => `  '${name.replaceAll("'", "\\'")}',`),
    '])',
    '',
  ].join('\n')
}

function main(): void {
  const generated = render(collectEventTypes())
  const destination = resolve(root, output)

  if (process.argv.includes('--check')) {
    let current: string | undefined
    try {
      current = readFileSync(destination, 'utf8')
    } catch {
      current = undefined
    }
    if (current !== generated) {
      console.error(`gen-session-event-types: ${output} is stale`)
      process.exitCode = 1
      return
    }
    console.log(`gen-session-event-types: ${output} is up to date`)
    return
  }

  writeFileSync(destination, generated)
  console.log(`gen-session-event-types: wrote ${output}`)
}

main()
