import { spawnSync } from 'node:child_process'
import { readFileSync, rmSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const repositoryRoot = fileURLToPath(new URL('..', import.meta.url))
const tsxCli = fileURLToPath(new URL('../node_modules/tsx/dist/cli.mjs', import.meta.url))
const output = new URL('../packages/core/session/src/known-event-types.ts', import.meta.url)

function runCheck() {
  return spawnSync(
    process.execPath,
    [tsxCli, 'scripts/gen-session-event-types.ts', '--check'],
    { cwd: repositoryRoot, encoding: 'utf8' },
  )
}

describe('Session event type generator', () => {
  it('checks the committed runtime vocabulary without rewriting it', () => {
    const before = readFileSync(output, 'utf8')
    const result = runCheck()

    expect(result.error).toBeUndefined()
    expect(result.status, `${result.stdout}${result.stderr}`).toBe(0)
    expect(readFileSync(output, 'utf8')).toBe(before)
    expect(before).toContain('Generated by scripts/gen-session-event-types.ts')
    expect(before).not.toContain('gen-persistence-catalog')
    expect(before).not.toContain('doc-sync')
  })

  it('rejects a newly declared event until the runtime vocabulary is regenerated', () => {
    const probe = new URL('../packages/util/brand/src/session-event-probe.ts', import.meta.url)
    writeFileSync(probe, `
declare module '@deepseek-ai/dsh-session/types' {
  interface SessionEventMap {
    'openloop/probe': { value: string }
  }
}

export {}
`)

    try {
      const result = runCheck()
      const combined = `${result.stdout}${result.stderr}`
      expect(result.error).toBeUndefined()
      expect(result.status, combined).toBe(1)
      expect(combined).toContain('known-event-types.ts')
    } finally {
      rmSync(probe, { force: true })
    }
  })
})
